plugins:
  timeline_sidebar_enabled:
    default: true
    client: true
  timeline_sidebar_lohn_url:
    default: "https://vsao-zh.ch/lohnrechner/?return"
    client: true
  timeline_sidebar_enamble_slider:
    default: true
    client: true
  timeline_sidebar_rss_url:
    default: "https://www.infonlinemed.ch/rss.cfm?pressespiegel=410A9985E70AEC84242C59E2768258DF"
    client: true